name: Metrics

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          output: ./metrics.svg  # Gera o arquivo "metrics.svg"
